### ISSUE TITLE
GroupCRUD

### ISSUE THREAD

**Issue by r-miyamae** [maetarou/GatherGram#1]

**Comment by r-miyamae** [comment]
Group
- 作成
- 詳細
- 編集
- 削除

**Comment by r-miyamae** [comment]
そもそもGroupってなんやっけ？
Gatherとは別の団体を指すやつ？(ITCとか)

**Comment by t-kusakabe** [comment]
そうやね。
groupはITCとかが分類されて、そのgroupに所属するのはITCの人間だけって感じ。
でもgatherってイベントみたいなものだからそれに参加するのはITC以外の人間でも良くて、そういうのをgatherと称してる的なw

**Comment by r-miyamae** [comment]
主催が誰かわかりやすい的な？
Group所属者がGather作るとそいつが属しているGroupと同じGroupメンバーが自動でGatherに加わる？
加わらないならあまり作る意味ない感じもする…

**Comment by t-kusakabe** [comment]
groupあとで！
