### ISSUE TITLE
Docker on gather

### ISSUE THREAD

**Issue by t-kusakabe** [maetarou/GatherGram#6]
- ただの自己満
- ホスト汚したくない
- 環境によるエラーがめんどくさい

**Comment by r-miyamae** [comment]
DockerをUbuntuで使うメリットがよくわからないマン

**Comment by t-kusakabe** [comment]
railsでdockerを使わない理由がないねんなあ。
前さんとかmysqlこの前エラってたりしたのがなくなるな。
あとは環境依存が起こらんから、環境構築が全て不要is幸せ。

**Comment by r-miyamae** [comment]
本番環境と同じイメージをそれぞれ使う感じよね？
まあ俺はもうシンボリックリンク貼ったしどっちでもいいかのう

**Comment by t-kusakabe** [comment]
まあ、dockerの利便性を見せつけてやろう💪

**Comment by r-miyamae** [comment]
使ったことあるけど、自分のローカルのmysqlとポート番号被ったりしてメリットがよくわからなかったｗ

**Comment by t-kusakabe** [comment]
被らんようにしますねwwwww

**Comment by t-kusakabe** [comment]
# 構成
- RoR
  - ruby:2.4.0-alpine
- db
  - mysql:5.7

**Comment by t-kusakabe** [comment]
結果...

- RoR
  - ruby:2.4.0-alpine
- react
  - node:9.1.0-alpine
- db
  - mysql:5.7-alpine


で、落ち着いた
